refactor: improve math
gohugoio/hugo pull request #10638
Opened 2023-01-22 04:36 UTC by septs

allow multi numbers of add (`+`) / sub (`-`) / mul (`*`) / div (`/`) / min value / max value

refactor after:

```
add 1 2 | add 3 | add 4
sub 1 2 | sub 3 | sub 4
mul 1 2 | mul 3 | mul 4
math.Min 1 2 | math.Min 3 | math.Min 4
math.Max 1 2 | math.Max 3 | math.Max 4
```

refactor before:

```
add 1 2 3 4
sub 1 2 3 4
mul 1 2 3 4
math.Min 1 2 3 4
math.Max 1 2 3 4
```

2023-01-22 04:44 UTC, septs commented
apply e.g: fit image dimension

after:

```
math.Min (div $maxWidth / .Width) (div $maxHeight / .Height) | math.Min 1
```

before:

```
math.Min (div $maxWidth / .Width) (div $maxHeight / .Height) 1
```

2023-01-26 14:38 UTC, bep commented
OK, this I like. What do you think, @jmooring ?

2023-01-26 20:51 UTC, jmooring commented
I have tested it. Looks good to me, though we might add some test cases, one with 3 arguments to each of the 6 functions.

2023-03-01 17:11 UTC, bep requested changes
OK, I like this change.

Could you 

* add some basic test cases to cover this
* adjust the Godoc and also the Markdown docs below /docs

2023-03-11 10:18 UTC, bep approved these changes

2023-03-11 10:21 UTC, merged