resources/images: Create AutoOrient image filter
gohugoio/hugo pull request #11819
Opened 2023-12-19 07:18 UTC by jmooring

Closes #11717

2023-12-19 07:55 UTC, jmooring commented
To test:

```text
git clone --single-branch -b hugo-github-issue-11717 https://github.com/jmooring/hugo-testing hugo-github-issue-11717
cd hugo-github-issue-11717
hugo server
```

I was unable to change the length of the filters slice without errors, nor was I able to return a nil filter. Returning a noop filter seemed reasonable. The gift package does not provide a noop filter, but this is effectively a noop:
```
// Return a noop filter.
return gift.Brightness(0)
```

2023-12-19 10:01 UTC, bep requested changes

2023-12-19 16:46 UTC, jmooring commented on resources/images/auto_orient.go
> +			return filters[orientation]
Done.

2023-12-19 16:51 UTC, jmooring commented on resources/images/auto_orient.go
> +	return gift.Brightness(0)
> returned nil here and removed it from the filter slice on the receiving end

That was my first approach, but reducing the number of elements in the filter slice caused errors elsewhere:

>  executing "index.html" at <images.Filter>: error calling Filter: runtime error: slice bounds out of range [2:1]

I try to track that down when I have some more time.

2023-12-20 01:38 UTC, jmooring commented on resources/images/auto_orient.go
> +	return gift.Brightness(0)
Done

2023-12-20 13:18 UTC, merged