Update minify library and switch to KeepSpecialComments option
gohugoio/hugo pull request #11880
Opened 2024-01-11 21:31 UTC by jtatum

KeepConditionalComments was deprecated in the upstream library and replaced with KeepSpecialComments. This new option reflects that both conditional comments and Server Side Include comments can be optionally stripped by the minifier. As with KeepConditionalComments, the minifier is configured not to strip them by default.

2024-01-11 21:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gohugoio/hugo?pullRequest=11880) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gohugoio/hugo?pullRequest=11880) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gohugoio/hugo?pullRequest=11880) it.</sub>

2024-01-14 15:49 UTC, jmooring requested changes
This change is not backward compatible. If you have this in your site config:

```text
[minify.tdewolff.html]
keepConditionalComments = false
```

The conditional comments will still be present.

Also, with this:

```text
[minify.tdewolff.html]
keepConditionalComments = true
```

...the console is flooded with the message below, once for every page:

> DEPRECATED: KeepConditionalComments is replaced by KeepSpecialComments

2024-01-15 17:00 UTC, jtatum commented
> This change is not backward compatible. If you have this in your site config:
> 
> 
> 
> ```text
> 
> [minify.tdewolff.html]
> 
> keepConditionalComments = false
> 
> ```
> 
> 
> 
> The conditional comments will still be present.
> 
> 
> 
> Also, with this:
> 
> 
> 
> ```text
> 
> [minify.tdewolff.html]
> 
> keepConditionalComments = true
> 
> ```
> 
> 
> 
> ...the console is flooded with the message below, once for every page:
> 
> 
> 
> > DEPRECATED: KeepConditionalComments is replaced by KeepSpecialComments
> 
> 

@jmooring The deprecated message comes from the upstream library, which essentially collapsed the KeepConditionalComments option into the KeepSpecialComments option. We can add a special case to automatically set KeepSpecialComments false if KeepConditionalComments is false? Would that make sense? It's a little more than what the user requested...

2024-01-15 17:44 UTC, jtatum commented
@jmooring I think this should do it, and I validated that both keepconditionalcomments = false and = true work in config.

2024-01-15 18:08 UTC, jtatum commented
> When both are present in config, the newer one must win, e.g.
> 
> ```
> keepConditionalComments = false
> keepSpecialComments = true
> ```

If anything, this should be an error. The upstream library does not have separate code for keepSpecialComments vs keepConditionalComments - they're treated as the same option. Not sure I see the value in handling setting both? Is there precedent for doing this, or raising a config error like this to the user?

2024-01-15 18:46 UTC, jmooring commented
This now works as expected. Couple of other things...

1\) While the body's open, do the same thing for decimal/precision handling (currently the old one wins), something like:

<details>
<summary>minifiers/config.go</summary>

```text
for _, key := range []string{"css", "svg"} {
	if v, found := tdm[key]; found {
		vm := maps.ToStringMap(v)
		ko := "decimal"
		kn := "precision"
		if vv, found := vm[ko]; found {
			if _, found = vm[kn]; !found {
				vvi := cast.ToInt(vv)
				if vvi > 0 {
					vm[kn] = vvi
				}
			}
			delete(vm, ko)
		}
	}
}

if v, found := tdm["html"]; found {
	vm := maps.ToStringMap(v)
	ko := "keepconditionalcomments"
	kn := "keepspecialcomments"
	if vv, found := vm[ko]; found {
		if _, found = vm[kn]; !found {
			vm[kn] = cast.ToBool(vv)
		}
		delete(vm, ko)
	}
}
```
</details>


2\) Change the commit message and PR title to "deps: Update github.com/tdewolff/minify/v2 v2.20.9 => v2.20.14". This is consistent with how we've handled these before.

3\) Open an a new issue about deprecating all three keys.

2024-01-17 04:20 UTC, jmooring approved these changes

2024-01-17 13:47 UTC, jmooring commented
@jtatum Thanks, this works great. I'm sure bep will review/merge this when convenient.

2024-01-18 13:15 UTC, jtatum commented
> @jtatum Thanks, this works great. I'm sure bep will review/merge this when convenient.

Thank you for all the mentorship! I appreciate your time.

2024-01-25 18:33 UTC, merged