math: Add exponential and trigonometric functions
gohugoio/hugo pull request #12660
Opened 2024-07-16 15:52 UTC by raoulb

Add `Exp` and `Sin`/`Cos` functions to math for use in templates.

Rationale:
- There is already `Log` so also having `Exp` seems to be expected.
- `Sin`/`Cos` always comes in handy when dealing with rotations. (F.e. in context of the image processing functions.)

2024-07-16 15:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gohugoio/hugo?pullRequest=12660) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gohugoio/hugo?pullRequest=12660) before we can accept your contribution.<br/><hr/>**Ral** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gohugoio/hugo?pullRequest=12660) it.</sub>

2024-07-17 09:56 UTC, bep commented
This looks good and I guess useful to enough people to me. What's your take @jmooring ?

2024-07-17 15:47 UTC, jmooring commented
If we're going to add trig functions, we should add these as well:
<https://github.com/gohugoio/hugo/issues/10857>

Also, given the infrequent use (this is only the second request I've seen), it would be better if these were not aliased.

2024-07-17 23:36 UTC, raoulb commented
Ok, I'll update the PR with the other functions.

Should I remove the aliased variants?

2024-07-17 23:40 UTC, phuchau1989 approved these changes

2024-07-20 17:46 UTC, jmooring requested changes
Once you made the changes and compiled, run "hugo gen docshelper" to update the data.yaml file.

2024-07-20 17:46 UTC, jmooring commented on docs/content/en/functions/math/ToDegrees.md
> +{{< new-in 0.129.0 >}}
```suggestion
{{< new-in 0.130.0 >}}
```

2024-07-20 17:46 UTC, jmooring commented on docs/content/en/functions/math/ToRadians.md
> +{{< new-in 0.129.0 >}}
```suggestion
{{< new-in 0.130.0 >}}
```

2024-07-20 17:46 UTC, jmooring commented on docs/content/en/functions/math/ToRadians.md
> +{{ math.ToRadians 1.5707963267948966 }} → 90
```suggestion
{{ math.ToRadians 90 }} → 1.5707963267948966
```

2024-07-20 17:46 UTC, jmooring commented on tpl/math/math.go
> +// Acos returns the arccosine function of the number n.
```suggestion
// Acos returns the arccosine, in radians, of n.
```

2024-07-20 17:46 UTC, jmooring commented on tpl/math/math.go
> +// Asin returns the arcsine function of the number n.
```suggestion
// Asin returns the arcsine, in radians, of n.
```

2024-07-20 17:46 UTC, jmooring commented on tpl/math/math.go
> +// Atan returns the arctangent function of the number n.
```suggestion
// Atan returns the arctangent, in radians, of n.
```

2024-07-20 17:46 UTC, jmooring commented on tpl/math/math.go
> +// Atan returns the arctangent function of the numbers n and m, determining the correct quadrant.
```suggestion
// Atan2 returns the arc tangent of n/m, using the signs of the two to determine the quadrant of the return value.
```

2024-07-20 17:46 UTC, jmooring commented on tpl/math/math.go
> +// Cos returns the cosine function of the number n.
```suggestion
// Cos returns the cosine of the radian argument n.
```

2024-07-20 17:46 UTC, jmooring commented on tpl/math/math.go
> +// E returns the number constant E.
```suggestion
// Returns the mathematical constant e.
```

2024-07-20 17:46 UTC, jmooring commented on tpl/math/math.go
> +// Exp returns the exponential function of the number n.
```suggestion
// Exp returns the base-e exponential of n.
```

2024-07-20 17:46 UTC, jmooring commented on tpl/math/math.go
> +// Returns the golden ratio constant Phi.
```suggestion
// Returns the golden ratio constant phi.
```

2024-07-20 17:46 UTC, jmooring commented on tpl/math/math.go
> +// Pi returns the number constant pi.
```suggestion
// Pi returns the mathematical constant pi.
```

2024-07-20 17:46 UTC, jmooring commented on tpl/math/math.go
> +// Sin returns the sine function of the number n.
```suggestion
// Sin returns the sine of the radian argument n.
```

2024-07-20 17:46 UTC, jmooring commented on tpl/math/math.go
> +// Tan returns the tangent function of the number n.
```suggestion
// Tan returns the tangent of the radian argument n.
```

2024-07-20 17:46 UTC, jmooring commented on tpl/math/math.go
> +		return 0, errors.New("Acos operator can't be used with non integer or float value")
```suggestion
		return 0, errors.New("requires a numeric argument")
```

2024-07-20 17:46 UTC, jmooring commented on tpl/math/math.go
> +		return 0, errors.New("Asin operator can't be used with non integer or float value")
```suggestion
		return 0, errors.New("requires a numeric argument")
```

2024-07-20 17:46 UTC, jmooring commented on tpl/math/math.go
> +		return 0, errors.New("Atan operator can't be used with non integer or float value")
```suggestion
		return 0, errors.New("requires a numeric argument")
```

2024-07-20 17:46 UTC, jmooring commented on tpl/math/math.go
> +		return 0, errors.New("Atan2 operator can't be used with non integer or float value")
```suggestion
		return 0, errors.New("requires a numeric argument")
```

2024-07-20 17:46 UTC, jmooring commented on tpl/math/math.go
> +		return 0, errors.New("Atan2 operator can't be used with non integer or float value")
```suggestion
		return 0, errors.New("requires a numeric argument")
```

2024-07-20 17:46 UTC, jmooring commented on tpl/math/math.go
> +		return 0, errors.New("Cos operator can't be used with non integer or float value")
```suggestion
		return 0, errors.New("requires a numeric argument")
```

2024-07-20 17:46 UTC, jmooring commented on tpl/math/math.go
> +		return 0, errors.New("Log2 operator can't be used with non integer or float value")
```suggestion
		return 0, errors.New("requires a numeric argument")
```

2024-07-20 17:46 UTC, jmooring commented on tpl/math/math.go
> +		return 0, errors.New("Log10 operator can't be used with non integer or float value")
```suggestion
		return 0, errors.New("requires a numeric argument")
```

2024-07-20 17:46 UTC, jmooring commented on tpl/math/math.go
> +		return 0, errors.New("Exp operator can't be used with non integer or float value")
```suggestion
		return 0, errors.New("requires a numeric argument")
```

2024-07-20 17:46 UTC, jmooring commented on tpl/math/math.go
> +		return 0, errors.New("Sin operator can't be used with non integer or float value")
```suggestion
		return 0, errors.New("requires a numeric argument")
```

2024-07-20 17:46 UTC, jmooring commented on tpl/math/math.go
> +		return 0, errors.New("Tan operator can't be used with non integer or float value")
```suggestion
		return 0, errors.New("requires a numeric argument")
```

2024-07-20 17:46 UTC, jmooring commented on tpl/math/math.go
> +		return 0, errors.New("the math.ToDegrees function requires a numeric argument")
```suggestion
		return 0, errors.New("requires a numeric argument")
```

2024-07-20 17:46 UTC, jmooring commented on tpl/math/math.go
> +		return 0, errors.New("the math.ToRadians function requires a numeric argument")
```suggestion
		return 0, errors.New("requires a numeric argument")
```

2024-07-20 18:09 UTC, bep commented
@raoulb A general remark: I will squash all the commit into one when merging (I will make sure the commit message looks good), so if you push the "commit suggestion" buttons above, everything will be fine in the end with the correct attributions.

2024-07-21 20:35 UTC, raoulb commented
> Once you made the changes and compiled, run "hugo gen docshelper" to update the data.yaml file.

Thanks, I did not know about the docshelper :D

2024-07-21 20:36 UTC, raoulb commented
> @raoulb A general remark: I will squash all the commit into one when merging (I will make sure the commit message looks good), so if you push the "commit suggestion" buttons above, everything will be fine in the end with the correct attributions.

I did some more rebase and squash. Feel free to merge this all in one single commit if you like.

2024-07-21 20:37 UTC, raoulb commented
Thanks for the review. I think I fixed everything now. Sorry for all the copy-paste errors :-/

2024-07-22 13:26 UTC, jmooring commented
Please remove `math.Cbrt` and all references to it. If someone actually needs to perform this calculation they can use `math.Pow` with a fractional exponent. As a general note, adding more functionality in the middle of a review cycle is annoying.

2024-07-24 00:07 UTC, raoulb commented
> Please remove `math.Cbrt` and all references to it.

Done.

> If someone actually needs to perform this calculation they can use `math.Pow` with a fractional exponent. 

True, but this also goes for `Sqrt` and some other things. I like a batteries-included 
concept. Scoped in the appropriate namespace it doesn't really have a cost impact for Hugo.

> As a general note, adding more functionality in the middle of a review cycle is annoying.

Sorry about that.

2024-07-24 10:07 UTC, bep commented
OK, we need to touch base on the scope of this PR. 

This started out as "Exp and Sin/Cos".

Then the funcs from #10857 was added:

```
math.Acos
math.Asin
math.Atan
math.Cos
math.Sin
math.Tan
math.Pi
```


That's 8 funcs. I count 16 in this PR. Where did the additional funcs come from and are they really must haves? /cc @jmooring

2024-07-25 14:52 UTC, raoulb commented
Yes, there are some more functions than initially planned. As I started wrapping the math library I found some more things that I think were missing.

It's about a relatively complete support for the Exp/Log pairs and the Trig/InvTrig pairs and some related helpers mentioned in the Issue/Forum post. For those I think it's just natural to expect to have them all. And I added Phi which I can imagine be useful for layout purposes.

Are they all really a *must have*? Depends, maybe, maybe not. But I'd rather like to have them if in doubt than miss them (and wait for an issues until someone needs them).

Again, as I already said: I'm all in favor of a batteries-included approach. In this case I don;t see any real downsides. All is properly put into the Math namespace, so does not clutter general scope for users. It's relatively little code that should require virtually no maintenance as it just wraps the Go std lib.

But if you disagree, fell free to cherry pick single commits (that's why it's still mostly single commits per topic) or I can split up the PR further and let some parts open for later.

2024-07-26 17:44 UTC, bep commented
@raoulb OK, thanks for the explanation. It's incredibly hard to review a PR that's suddenly expanding/doubling in scope. What I suggest is this:

Reduce this PR to the 8 funcs listed above. Then create a PR #2 with the additional funcs.

2024-07-27 02:01 UTC, raoulb commented
Yeah, maybe I should have stated to goal differently. I'd like to add some basic math functions to Hugo which are useful in general. I'll now split this PR into smaller chunks of code which implement functions that mathematically belong together.

2024-07-27 02:03 UTC, raoulb commented
This PR now contains trig and inv-trig functions only. This closes issue https://github.com/gohugoio/hugo/issues/10857.

2024-07-31 22:28 UTC, raoulb commented
I guess this is done now. Thanks for merging.

2024-07-31 22:28 UTC, closed without merging